name: quotez
description: A new Flutter project.
publish_to: 'none'

version: 0.2.0+3

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # UI
  sliding_up_panel: ^2.0.0+1

  # BLoC
  bloc: ^8.0.3
  bloc_test: ^9.0.3
  flutter_bloc: ^8.0.1

  # Network
  dio: ^4.0.6

  #Database
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  #Utils
  equatable: ^2.0.3
  share_plus: ^4.0.4
  intl: ^0.17.0
  shimmer_animation: ^2.1.0+1
  open_mail_app: ^0.4.5
  url_launcher: ^6.1.0
  connectivity_plus: ^2.3.0
  import_sorter: ^4.6.0
  mocktail: ^0.3.0
  package_info_plus: ^1.4.2
  flutter_native_splash: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.2
  build_runner: ^2.1.8
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  dart_code_metrics: ^4.15.2

import_sorter:
  comments: false

flutter_native_splash:
  color: '#55CD96'

flutter:
  assets:
    - assets/

  uses-material-design: true